version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: adsfinal-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Root@2345!
      MYSQL_DATABASE: ads_dental
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: adsfinal-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ads_dental
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root@2345!
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
